# Generated by Django 5.2.5 on 2025-09-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='напишите задачу')),
                ('choice_type', models.CharField(choices=[('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено')], max_length=100, verbose_name='выберите вариант')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
