# Generated by Django 5.2.5 on 2025-09-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='укажите название блога')),
                ('images', models.ImageField(upload_to='blog/', verbose_name='загрузите фото')),
                ('description', models.TextField(verbose_name='укажите описание блога')),
                ('link_blog', models.URLField(verbose_name='вставьте доп ссылку на контент')),
                ('category_blog', models.CharField(choices=[('Машины', 'Машины'), ('Недвижимость', 'Недвижимость'), ('Кино', 'Кино')], default='Кино', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
