# Generated by Django 5.2.5 on 2025-09-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='укажите ссылку с youTube'),
        ),
    ]
