# Generated by Django 5.2.5 on 2025-09-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='оставьте отзыв')),
                ('stars', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='⭐⭐⭐⭐', max_length=100, verbose_name='поставьте оценку об блоге')),
                ('choice_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.blog', verbose_name='выберите пост для коммента')),
            ],
            options={
                'verbose_name': 'коммент',
                'verbose_name_plural': 'комменты',
            },
        ),
    ]
