# Generated by Django 5.2.5 on 2025-09-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='marks',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=100, null=True),
        ),
    ]
